fpl:
  api:
    base-uri: https://fantasy.premierleague.com/api/
  path:
    bootstrap: /bootstrap-static/
    fixtures: /fixtures/
    players:
      summary: /element-summary/{player-id}/
      live: /event/{GW}/live/
    managers:
      team: /entry/{team-id}/
      transfer: /entry/{team-id}/transfers/
      pick: /entry/{team-id}/event/{GW}/picks/
      history: /entry/{team-id}/history/
    leagues:
      classic: /leagues-classic/{league-id}/standings/
      head-to-head: /leagues-h2h-matches/league/{league-ID}/

quarkus:
  rest-client:
    io.github.aj8gh.fplcrunch.client.FplClient:
      url: ${fpl.api.base-uri}
