quarkus:
  rest:
    path: api
  log:
    level: INFO
  rest-client:
    io.github.aj8gh.fplcrunch.client.FplApiClient:
      url: http://localhost:8888
    io.github.aj8gh.fplcrunch.client.FplAccountClient:
      url: http://localhost:8888

accounts:
  login: abc@testing.com
  password: password
