package io.github.aj8gh.fplcrunch.client.model.response.bootstrap;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import java.math.BigDecimal;
import java.time.Instant;
import lombok.Builder;

@Builder(toBuilder = true)
@JsonNaming(SnakeCaseStrategy.class)
public record Element(
    Integer chanceOfPlayingNextRound,
    Integer chanceOfPlayingThisRound,
    Integer code,
    Integer costChangeEvent,
    Integer costChangeEventFall,
    Integer costChangeStart,
    Integer costChangeStartFall,
    Integer dreamteamCount,
    Integer elementType,
    BigDecimal epNext,
    BigDecimal epThis,
    Integer eventPoints,
    String firstName,
    BigDecimal form,
    Integer id,
    Boolean inDreamteam,
    String news,
    Instant newsAdded,
    Integer nowCost,
    String photo,
    BigDecimal pointsPerGame,
    String secondName,
    BigDecimal selectedByPercent,
    Boolean special,
    Integer squadNumber,
    String status,
    Integer team,
    Integer teamCode,
    Integer totalPoints,
    Integer transfersIn,
    Integer transfersInEvent,
    Integer transfersOut,
    Integer transfersOutEvent,
    BigDecimal valueForm,
    BigDecimal valueSeason,
    String webName,
    Integer minutes,
    Integer goalsScored,
    Integer assists,
    Integer cleanSheets,
    Integer goalsConceded,
    Integer ownGoals,
    Integer penaltiesSaved,
    Integer penaltiesMissed,
    Integer yellowCards,
    Integer redCards,
    Integer saves,
    Integer bonus,
    Integer bps,
    BigDecimal influence,
    BigDecimal creativity,
    BigDecimal threat,
    BigDecimal ictIndex,
    Integer starts,
    BigDecimal expectedGoals,
    BigDecimal expectedAssists,
    BigDecimal expectedGoalInvolvements,
    BigDecimal expectedGoalsConceded,
    Integer influenceRank,
    Integer influenceRankType,
    Integer creativityRank,
    Integer creativityRankType,
    Integer threatRank,
    Integer threatRankType,
    Integer ictIndexRank,
    Integer ictIndexRankType,
    Integer cornersAndIndirectFreekicksOrder,
    String cornersAndIndirectFreekicksText,
    Integer directFreekicksOrder,
    String directFreekicksText,
    Integer penaltiesOrder,
    String penaltiesText,
    @JsonAlias("expected_goals_per_90") Integer expectedGoalsPer90,
    @JsonAlias("saves_per_90") Integer savesPer90,
    @JsonAlias("expected_assists_per_90") Integer expectedAssistsPer90,
    @JsonAlias("expected_goal_involvements_per_90") Integer expectedGoalInvolvementsPer90,
    @JsonAlias("expected_goals_conceded_per_90") Integer expectedGoalsConcededPer90,
    @JsonAlias("goals_conceded_per_90") Integer goalsConcededPer90,
    Integer nowCostRank,
    Integer nowCostRankType,
    Integer formRank,
    Integer formRankType,
    Integer pointsPerGameRank,
    Integer pointsPerGameRankType,
    Integer selectedRank,
    Integer selectedRankType,
    @JsonAlias("starts_per_90") Integer startsPer90,
    @JsonAlias("clean_sheets_per_90") Integer cleanSheetsPer90
) {

}
